version: '3'
services:
  wowonder:
    build:
      context: .
      dockerfile: Dockerfile
    image: wowonder4.2
    ports:
      - "8080:80"
    volumes:
      - wowonder-data:/var/www/html/wowonder
      - .:/var/www/html/wowonder
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root

volumes:
  wowonder-data:
  mysql-data:
